apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: testapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

    #progressDeadlineSeconds: 600

  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - image: elsiedev/flask-app:latest
          imagePullPolicy: Always
          name: testapp
          ports:
            - containerPort: 80
